LINKLION-KNU/NEWSPACT-SERVER

.idea/compiler.xml
.idea/workspace.xml
src/main/java/org/likelion/newsfactbackend/company/domain/MediaCompany.java
src/main/java/org/likelion/newsfactbackend/company/repository/MediaCompanyRepository.java
src/main/java/org/likelion/newsfactbackend/global/domain/enums/loginType.java
src/main/java/org/likelion/newsfactbackend/keyword/domain/TrendKeyword.java
src/main/java/org/likelion/newsfactbackend/keyword/repository/TrendKeywordRepository.java
src/main/java/org/likelion/newsfactbackend/news/domain/News.java
src/main/java/org/likelion/newsfactbackend/news/repository/NewsRepository.java

1. company(언론사), keyword(그날 키워드), news(기사) entity 생성
2. entity 대응 repository 생성

Feat hand mk entity

---

.idea/workspace.xml
src/main/java/org/likelion/newsfactbackend/news/chosun/dto/request/ChosunNewsRequestDto.java
src/main/java/org/likelion/newsfactbackend/news/chosun/dto/response/ChosunNewsResponseDto.java
src/main/java/org/likelion/newsfactbackend/news/chosun/service/ChosunNewsService.java
src/main/java/org/likelion/newsfactbackend/news/chosun/service/impl/ChosunNewsServiceImpl.java

ChosunNews dto

---

src/main/java/org/likelion/newsfactbackend/domain/news/domain/News.java
src/main/java/org/likelion/newsfactbackend/domain/news/repository/NewsRepository.java

기능: news entity, news repository 생성

✨ create news entity repository

---

.idea/.gitignore
src/main/java/org/likelion/newsfactbackend/domain/auth/controller/AuthController.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/AuthDAO.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dto/request/RequestSignInDto.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dto/request/RequestSignUpDto.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dto/response/ResponseAuthDto.java
src/main/java/org/likelion/newsfactbackend/domain/auth/service/AuthService.java
src/main/java/org/likelion/newsfactbackend/domain/auth/service/impl/AuthServiceImpl.java
src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
src/main/java/org/likelion/newsfactbackend/global/domain/enums/loginType.java
src/main/java/org/likelion/newsfactbackend/user/domain/User.java
src/main/java/org/likelion/newsfactbackend/user/repository/UserRepository.java

카카오 로그인 기능 개발
@agape1225 #16 
어떤 변경 사항이 있나요?

카카오 로그인 기능 개발

---

.idea/misc.xml
src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/Company.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/Keyword.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/request/RequestNewsDto.java

뉴스 컨트롤러 생성
#14 
어떤 변경 사항이 있나요?

뉴스 컨트롤러 생성

---

src/main/java/org/likelion/newsfactbackend/domain/keywords/dao/KeywordsDAO.java
src/main/java/org/likelion/newsfactbackend/domain/keywords/dao/impl/KeywordsDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/keywords/dto/response/ResponseKeywordsDto.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/ScrapsDAO.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/impl/ScrapsDAOImpl.java

DAO 인터페이스 메서드 추가
@agape1225 @tangerinem #21
어떤 변경 사항이 있나요?

DAO 인터페이스 메서드 정의

---

Dockerfile

- Newspact 서버 docker images 빌드 시 설정 파일 추가 close #30
어떤 변경 사항이 있나요?

:rocket: Add docker file

---

src/main/java/org/likelion/newsfactbackend/NewsFactBackendApplication.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
src/main/java/org/likelion/newsfactbackend/global/security/JwtTokenProvider.java
src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java
src/main/java/org/likelion/newsfactbackend/user/repository/UserRepository.java
src/main/java/org/likelion/newsfactbackend/user/service/impl/UserDetailsServiceImpl.java

- 소셜 로그인 시 유저 조회 수정
- security configuration 권한 uri 수정
- security filter token 유무 확인 수정
close #36
어떤 변경 사항이 있나요?

:bug: Fix jpa custom method

---

src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

✨ create news contentsList

---

pom.xml
src/main/java/org/likelion/newsfactbackend/domain/auth/controller/AuthController.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/AuthDAO.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dto/response/ResponseAuthDto.java
src/main/java/org/likelion/newsfactbackend/domain/auth/service/AuthService.java
src/main/java/org/likelion/newsfactbackend/domain/auth/service/impl/AuthServiceImpl.java
src/main/java/org/likelion/newsfactbackend/global/config/RedisConfig.java
src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
src/main/java/org/likelion/newsfactbackend/global/security/JwtAuthenticationFilter.java
src/main/java/org/likelion/newsfactbackend/global/security/JwtTokenProvider.java
src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java
src/main/java/org/likelion/newsfactbackend/user/domain/User.java

- 회원가입, 로그인 시 refresh token redis 저장 ex) {nickname : token}
- 로그아웃 시 refresh token redis 삭제
- 로그아웃 시 access token redis 추가 ex) {token : "logout"}
- JwtAuthenticationFilter 에서 redis storage token key 값 확인
close #40 
어떤 변경 사항이 있나요?

✨ Add logout function

---

src/main/java/org/likelion/newsfactbackend/domain/scraps/controller/ScrapsController.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/ScrapsDAO.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/impl/ScrapsDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/domain/Scraps.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/request/RequestSaveScrapsDto.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/response/ResponseScrapsNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/repository/ScrapsRepository.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/service/ScrapsService.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/service/impl/ScrapsServiceImpl.java
src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
src/main/java/org/likelion/newsfactbackend/user/domain/User.java

- 뉴스 스크랩 페이지 기능 개발
- 뉴스 스크랩 기능
- 스크랩 뉴스 조회 페이징 처리 기능
- 스크랩 뉴스 삭제 기능
close #42
어떤 변경 사항이 있나요?

:sparkles: Add scraps function

---

pom.xml
src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/RecommendNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

필요 없는 코드 삭제 및 추천 기사 4개 반환 (title, thumbnail, companyLogo, newsUrl)
Resolves: #43 
어떤 변경 사항이 있나요?

✨ create Recommend News

---

src/main/java/org/likelion/newsfactbackend/global/config/RedisConfig.java

- 배포 서버 redis 접근 시 server connect 실패
- 확인 결과 host : localhost default 로 지정되어 @Value 어노테이션 활용 하여 명시적으로 지정
close #49
어떤 변경 사항이 있나요?

:bug: Fix redis config

---

src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/AuthDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/auth/dao/impl/NicknameDAOImpl.java
src/main/java/org/likelion/newsfactbackend/global/domain/enums/ResultCode.java
src/main/java/org/likelion/newsfactbackend/global/security/JwtAuthenticationFilter.java
src/main/java/org/likelion/newsfactbackend/global/security/SecurityConfiguration.java

- 닉네임 생성 시 상수 변경
- 머지 시 Result Code 중복 오류 해결
- 회원가입 후 반환 시, nickname -> user name 변경
- Jwt 토큰 유무 검사 pass url main page 추가
- Resource 도메인 한정 변경 ex) https://newspect.co.kr/
close [#47](https://github.com/LINKLION-KNU/NEWSPACT-SERVER/issues/47)
어떤 변경 사항이 있나요?

:art: Change variable name

---

src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

카테고리 별 뉴스 기사 조회
Resolves: #46 
어떤 변경 사항이 있나요?

✨ create news category

---

src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

이미 newsUrl로 동일한 값이 있어 ResponseNewsDto 내부 sid, articleUrl 값 삭제
close: #53
어떤 변경 사항이 있나요?

🔥 remove dto sid, articleUrl

---

src/main/java/org/likelion/newsfactbackend/domain/news/controller/NewsController.java
src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsAnalysisDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/NewsService.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/controller/ScrapsController.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dao/impl/ScrapsDAOImpl.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/domain/Scraps.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/request/RequestSaveScrapsDto.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/dto/response/ResponseScrapsNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/scraps/repository/ScrapsRepository.java
src/main/java/org/likelion/newsfactbackend/global/security/JwtAuthenticationFilter.java

- RestTemplate 객체 사용하여 ai 서버 api 호출
- response 값 ObjectMapper 로 정제
- scraps 생성, 조회 시 필드 값 추가 (companyLogo, category)
- crawling 시 태그 삭제 로직 변경
close #55 
어떤 변경 사항이 있나요?

✨ AI server connect

---

src/main/java/org/likelion/newsfactbackend/user/domain/User.java

- google login 시 profile url 길이가 많이 길면, 회원가입이 안되는 버그 수정
close #57 
어떤 변경 사항이 있나요?

:bug: Fix profile url bug

---

src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

html tag 삭제 로직 추가
Resolves: #60
close: #62
어떤 변경 사항이 있나요?

🐛 fix remove html tag

---

src/main/java/org/likelion/newsfactbackend/domain/news/dto/response/ResponseNewsDto.java
src/main/java/org/likelion/newsfactbackend/domain/news/service/impl/NewsServiceImpl.java

뉴스 상세페이지를 반환할 때 기사 본문 내에 여러개의 이미지를 저장하는 변수 및 코드 추가
Resolves: #61 
close: #61 
어떤 변경 사항이 있나요?

🐛 update multiple images
